#!/usr/bin/env node
/*
 *********************************************************************************
 *                     Copyright (C) 2018 wystan
 *
 *       filename: ftpserver.js
 *    description:
 *        created: 2018-04-19 16:43:45
 *         author: wystan
 *
 *********************************************************************************
 */

const ftp_srv = require('ftp-srv');
const ftpserver = new ftp_srv('ftp://0.0.0.0:2000');

ftpserver.on('login', (data, resolve, reject) => {
	resolve({root:"/home/winner/dl/gcc/gcc.gnu.org"});
});

ftpserver.listen()

/************************************* END **************************************/
