#!/usr/bin/env node
/*
 *********************************************************************************
 *                     Copyright (C) 2018 wystan
 *
 *       filename: ftpserver.js
 *    description:
 *        created: 2018-04-19 16:43:45
 *         author: wystan
 *
 *********************************************************************************
 */

const ftp_srv = require('ftp-srv');
const url = "ftp://10.1.250.214:21";

function main(argv) {
    if (argv.length < 3) {
        console.log("usage:", argv[1], "<rootdir>");
        return;
    }

    const ftpserver = new ftp_srv(url, {
        anonymous: true,
        pasv_range: 1000
    });
    ftpserver.on('login', (data, resolve, reject) => {
        resolve({root:process.argv[2]});
    });

    ftpserver.listen();
}

main(process.argv);

/************************************* END **************************************/
