#!/usr/bin/env node
/*
 *********************************************************************************
 *                     Copyright (C) 2018 wystan
 *
 *       filename: ftpserver.js
 *    description:
 *        created: 2018-04-18 22:48:56
 *         author: wystan
 *
 *********************************************************************************
 */

const ftpd = require('ftpd');

var server = new ftpd.FtpServer("0.0.0.0", {
    getInitialCwd: function () {
        return '/';
    },
    getRoot: function () {
        return process.cwd();
    },
    pasvPortRangeStart: 1025,
    pasvPortRangeEnd: 1050,
    tlsOptions: null,
    allowUnauthorizedTls: true,
    useWriteFile: false,
    useReadFile: false,
    uploadMaxSlurpSize: 7000 // N/A unless 'useWriteFile' is true.
});

server.on('error', function (error) {
    console.log('FTP Server error:', error);
});

server.on('client:connected', function (connection) {
    let username="";
    connection.on('command:user', function (user, success, failure) {
        username = user;
        success();
    });

    connection.on('command:pass', function (pass, success, failure) {
        success(username);
    });
});

server.debugging = 0;
server.listen(21);
console.log('Listening on port ' + 21);

/************************************* END **************************************/

